# Generated by Django 5.1 on 2024-10-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0002_alter_actore_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actore',
            name='films',
            field=models.ManyToManyField(null=True, related_name='films', to='KinoVibe.videofile'),
        ),
    ]
