# Generated by Django 5.1 on 2024-08-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0002_genre_remove_category_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video', models.FileField(null=True, upload_to='', verbose_name='/videos')),
            ],
        ),
    ]
