# Generated by Django 5.1 on 2024-08-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0003_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='video',
            field=models.FileField(null=True, upload_to='videos'),
        ),
    ]
