# Generated by Django 5.1 on 2024-10-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0004_remove_videofile_actore_personaj_videofile_actores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(max_length=100, verbose_name='каьера')),
            ],
            options={
                'verbose_name': 'каьера',
                'verbose_name_plural': 'профессии',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_country', models.CharField(max_length=100, verbose_name='страны')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
            },
        ),
        migrations.AddField(
            model_name='personaj',
            name='genre',
            field=models.ManyToManyField(to='KinoVibe.genre', verbose_name='genre'),
        ),
    ]
