# Generated by Django 5.1 on 2024-08-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0004_alter_videofile_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='background_image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
