# Generated by Django 5.1 on 2024-09-02 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0005_videofile_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='genre',
            field=models.ManyToManyField(to='KinoVibe.genre', verbose_name='genre'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='info',
            field=models.CharField(default='text', max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Actior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('date_borth', models.DateTimeField(auto_now_add=True)),
                ('date_dead', models.DateTimeField(auto_now_add=True)),
                ('films', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='KinoVibe.videofile')),
            ],
        ),
        migrations.AddField(
            model_name='videofile',
            name='actior',
            field=models.ManyToManyField(to='KinoVibe.actior'),
        ),
    ]
