# Generated by Django 5.1 on 2024-10-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0005_careers_country_personaj_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaj',
            name='date_dead',
            field=models.DateField(blank=True, null=True),
        ),
    ]
