# Generated by Django 5.1 on 2024-10-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0006_alter_personaj_date_dead'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaj',
            name='borthman',
            field=models.ManyToManyField(blank=True, related_name='personaj', to='KinoVibe.personaj'),
        ),
        migrations.AddField(
            model_name='personaj',
            name='country',
            field=models.ManyToManyField(blank=True, related_name='films', to='KinoVibe.country'),
        ),
        migrations.RemoveField(
            model_name='personaj',
            name='career',
        ),
        migrations.AddField(
            model_name='personaj',
            name='career',
            field=models.ManyToManyField(blank=True, related_name='careers', to='KinoVibe.careers'),
        ),
    ]
