# Generated by Django 5.1 on 2024-09-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0006_videofile_genre_videofile_info_actior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actior',
            name='profile',
            field=models.ImageField(default='t', upload_to='actior/'),
            preserve_default=False,
        ),
    ]
