# Generated by Django 5.1 on 2024-09-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0007_actior_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actior',
            name='films',
        ),
        migrations.AddField(
            model_name='actior',
            name='films',
            field=models.ManyToManyField(related_name='films', to='KinoVibe.videofile'),
        ),
    ]
