# Generated by Django 5.1 on 2024-10-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0008_careers_slug_country_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='рейтинг'),
        ),
    ]
