# Generated by Django 5.1 on 2024-09-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0008_remove_actior_films_actior_films'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actior',
            new_name='Actore',
        ),
    ]
