# Generated by Django 5.1 on 2024-11-13 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0009_videofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_movie', to='KinoVibe.videofile', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='rating',
            field=models.FloatField(default=0, verbose_name='рейтинг'),
        ),
    ]
