# Generated by Django 5.1 on 2024-09-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0010_alter_actore_date_borth_alter_actore_date_dead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actore',
            name='date_dead',
            field=models.DateField(null=True),
        ),
    ]
