# Generated by Django 5.1 on 2024-11-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0010_alter_review_movie_alter_videofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='рейтинг'),
        ),
    ]
