# Generated by Django 5.1 on 2024-09-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0011_alter_actore_date_dead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actore',
            name='date_dead',
            field=models.DateField(default='01/01/2001', null=True),
        ),
    ]
