# Generated by Django 5.1 on 2024-09-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0012_alter_actore_date_dead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='actior',
        ),
    ]
