# Generated by Django 5.1 on 2024-10-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0013_remove_videofile_actior'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='date',
            field=models.DateField(null=True, verbose_name='data_vypuska'),
        ),
    ]
