# Generated by Django 5.1 on 2024-10-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoVibe', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='actore',
            field=models.ManyToManyField(to='KinoVibe.actore', verbose_name='актеры'),
        ),
    ]
